CmsShoppingCart/Models/ViewModels/Shop/CategoryVM.cs
using CmsShoppingCart.Models.Data;
using System.ComponentModel.DataAnnotations;

namespace CmsShoppingCart.Models.ViewModels.Shop
{
	public class CategoryVM
	{
		public CategoryVM()
		{
		}

		public CategoryVM(CategoryDTO row)
		{
			Id = row.Id;
			Name = row.Name;
			Slug = row.Slug;
			Sorting = row.Sorting;
		}

		public int Id { get; set; }
		[Display(Name = "Name")]
		public string Name { get; set; }
		public string Slug { get; set; }
		public int Sorting { get; set; }
	}
}

CmsShoppingCart/Models/ViewModels/Shop/ProductVM.cs
using CmsShoppingCart.Models.Data;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CmsShoppingCart.Models.ViewModels.Shop
{
	public class ProductVM
	{
		public ProductVM()
		{}

		public ProductVM(ProductDTO row)
		{
			Id = row.Id;
			Name = row.Name;
			Slug = row.Slug;
			Description = row.Description;
			Price = row.Price;
			CategoryName = row.CategoryName;
			CategoryId = row.CategoryId;
			ImageName = row.ImageName;
		}

		public int Id { get; set; }
		[Required]
		public string Name { get; set; }
		public string Slug { get; set; }
		[Required]
		public string Description { get; set; }
		public decimal Price { get; set; }
		public string CategoryName { get; set; }
		[Required]
		[Display(Name = "Category")]
		public int CategoryId { get; set; }
		[Display(Name = "Product Image")]
		public string ImageName { get; set; }

		public IEnumerable<SelectListItem> Categories { get; set; }
		public IEnumerable<string> GalleryImages { get; set; }
	}
}

CmsShoppingCart/Areas/Admin/Controllers/ShopController.cs
using CmsShoppingCart.Models.Data;
using CmsShoppingCart.Models.ViewModels.Shop;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace CmsShoppingCart.Areas.Admin.Controllers
{
    public class ShopController : Controller
    {
		// GET: Admin/Shop/Categories
		public ActionResult Categories()
        {
			// Declare list of models
			List<CategoryVM> categories;

			using (Db db = new Db())
			{
				// Init the list
				categories = db.Categories.ToArray().OrderBy(x => x.Sorting).Select(x => new CategoryVM(x)).ToList();
			}

			//Return view with the list
            return View(categories);
        }

		// POST: Admin/Shop/AddNewCategory/categoryName
		[HttpPost]
		public string AddNewCategory(string categoryName)
		{
			// Declare id
			string id = null;

			using (Db db = new Db())
			{
				// Check that the category name is unique
				if (db.Categories.Any(x => x.Name == categoryName))
					return "titletaken";

				// Init DTO
				CategoryDTO dto = new CategoryDTO
				{
					// Add to DTO
					Name = categoryName,
					Slug = categoryName.Replace(" ", "-").ToLower(),
					Sorting = db.Categories.Count()
				};

				// Save DTO
				db.Categories.Add(dto);
				db.SaveChanges();

				//Get the id
				//id = db.Categories.LastOrDefault().Id.ToString();
				id = dto.Id.ToString();
			}

			// Return id
			return id;
		}

		// GET: Admin/Shop/DeleteCategory/id
		[HttpGet]
		public ActionResult DeleteCategory(int id)
		{
			using (Db db = new Db())
			{
				//Get the category
				CategoryDTO dto = db.Categories.Find(id);

				// Remove the category
				db.Categories.Remove(dto);

				// Save DTO              
				db.SaveChanges();
			}

			// Redirect
			return RedirectToAction("Categories");
		}

		//POST: /Admin/Shop/ReorderCategories
		[HttpPost]
		public void ReorderCategories(int[] id)
		{
			using (Db db = new Db())
			{
				// Set initial count
				int count = 1;

				// Declare CategoryDTO
				CategoryDTO dto;

				// Set sorting for each page
				foreach (var categoryId in id)
				{
					dto = db.Categories.Find(categoryId);
					dto.Sorting = count;

					db.SaveChanges();

					count++;
				}
			}
		}

		//POST: /Admin/Shop/RenameCategory
		[HttpPost]
		public string RenameCategory(int categoryId, string newCategoryName)
		{
			using (Db db = new Db())
			{
				// Check category name is unique
				if (db.Categories.Any(c => c.Name == newCategoryName))
					return "titletaken";

				// Get DTO
				CategoryDTO dto = db.Categories.Find(categoryId);

				// Edit DTO
				dto.Name = newCategoryName;

				// Save
				db.SaveChanges();
			}
			//Return
			return "The category name has changed!";
		}

		// GET: Admin/Shop/AddProduct
		[HttpGet]
		public ActionResult AddProduct()
		{
			//Init model
			ProductVM model = new ProductVM();

			// Add select list of categories to model
			using (Db db = new Db())
			{
				model.Categories = new SelectList(db.Categories.ToList(), "Id", "Name");
			}

			//Return view with model
			return View(model);
		}

		// POST: Admin/Shop/AddProduct
		[HttpPost]
		public ActionResult AddProduct(ProductVM model, HttpPostedFileBase file)
		{
			// Check model state
			if (!ModelState.IsValid)
				return AddProduct();

			// Make sure product name is unique
			using (Db db = new Db())
			{
				if (db.Products.Any(p => p.Name == model.Name))
				{
					ModelState.AddModelError("", "That product name is taken!");
					return AddProduct();
				}
			}

			// Declare product id 
			int id;

			// Init and save productDTO
			using (Db db = new Db())
			{
				ProductDTO dto = new ProductDTO
				{
					Name = model.Name,
					Slug = model.Name.Replace(" ", "-").ToLower(),
					Description = model.Description,
					Price = model.Price,
					CategoryId = model.CategoryId
				};

				CategoryDTO categoryDTO = db.Categories.FirstOrDefault(c => c.Id == model.CategoryId);
				dto.CategoryName = categoryDTO.Name;

				//Save
				db.Products.Add(dto);
				db.SaveChanges();

				// Get inserted id
				id = dto.Id;
			}

			// Set TempData message
			TempData["SM"] = "You have added a product!";

			#region Upload Image

			// Create necessary directories
			var originalDirectory = new DirectoryInfo(string.Format("{0}Images\\Uploads", Server.MapPath(@"\")));

			var pathString1 = Path.Combine(originalDirectory.ToString(), "Products\\");
			var pathString2 = Path.Combine(originalDirectory.ToString(), "Products\\" + id.ToString());
			var pathString3 = Path.Combine(originalDirectory.ToString(), "Products\\" + id.ToString() + "\\Thumbs");
			var pathString4 = Path.Combine(originalDirectory.ToString(), "Products\\" + id.ToString() + "\\Gallery");
			var pathString5 = Path.Combine(originalDirectory.ToString(), "Products\\" + id.ToString() + "\\Gallery\\Thumbs");

			if (!Directory.Exists(pathString1))
				Directory.CreateDirectory(pathString1);

			if (!Directory.Exists(pathString2))
				Directory.CreateDirectory(pathString2);

			if (!Directory.Exists(pathString3))
				Directory.CreateDirectory(pathString3);

			if (!Directory.Exists(pathString4))
				Directory.CreateDirectory(pathString4);

			if (!Directory.Exists(pathString5))
				Directory.CreateDirectory(pathString5);

			// Check if a file was uploaded
			if (file != null && file.ContentLength > 0)
			{
				// Get file extension
				string ext = file.ContentType.ToLower();

				// Verity extension
				if (ext != "image/jpg" &&
					ext != "image/jpeg" &&
					ext != "image/pjpeg" &&
					ext != "image/gif" &&
					ext != "image/x-png" &&
					ext != "image/png")
				{
					using (Db db = new Db())
					{
						model.Categories = new SelectList(db.Categories.ToList(), "Id", "Name");
						ModelState.AddModelError("", "The image was not uploaded - wrong image extension.");
						return View(model);
					}
				}

				// Init image name
				string imageName = file.FileName;

				// Save image name to DTO
				using (Db db = new Db())
				{
					ProductDTO dto = db.Products.Find(id);
					dto.ImageName = imageName;

					db.SaveChanges();
				}

				// Set original and thumb image paths
				var path = string.Format("{0}\\{1}", pathString2, imageName);
				var path2 = string.Format("{0}\\{1}", pathString3, imageName);

				// Save original
				file.SaveAs(path);

				// Create and save thumb
				WebImage img = new WebImage(file.InputStream);
				img.Resize(200, 200);
				img.Save(path2);

			}

			#endregion

			// Redirect
			return RedirectToAction("AddProduct");
		}

		// GET: /Admin/Shop/Products/page
		[HttpGet]
		public ActionResult Products(int? page, int? categoryId)
		{
			// Declare list of models
			List<ProductVM> products;

			// Set page number
			var pageNumber = page ?? 1;

			using (Db db = new Db())
			{
				// Init the list
				products = db.Products.ToArray()
					.Where(p => p.CategoryId == categoryId || categoryId == null || categoryId == 0)
					.Select(p => new ProductVM(p)).ToList();

				// Populate categories select list
				ViewBag.Categories = new SelectList(db.Categories.ToList(), "Id", "Name");

				// Set selected category
				ViewBag.SelectedCategory = categoryId.ToString();
			}

			// Set pagination
			var onePageOfProducts = products.ToPagedList(pageNumber, 4);
			ViewBag.OnePageOfProducts = onePageOfProducts;

			//Return view with the list
			return View(products);
		}

		// GET: Admin/Shop/EditProduct/id
		[HttpGet]
		public ActionResult EditProduct(int id)
		{
			// Declare productVM
			ProductVM model;

			using (Db db = new Db())
			{
				// Get the product
				ProductDTO dto = db.Products.Find(id);

				// Make sure product exists
				if (dto == null)
					return Content("This product does not exist.");

				// Init model
				model = new ProductVM(dto)
				{
					// Make a select list
					Categories = new SelectList(db.Categories.ToList(), "Id", "Name"),

					// Get all gallery images
					GalleryImages = Directory.EnumerateFiles(Server.MapPath("~/Images/Uploads/Products/" + id + "/Gallery/Thumbs"))
						.Select(fn => Path.GetFileName(fn))
				};
			}

			// Return view with model
			return View(model);
		}

		// POST: Admin/Shop/EditProduct
		[HttpPost]
		public ActionResult EditProduct(ProductVM model, HttpPostedFileBase file)
		{
			// Get product id
			int id = model.Id;

			// Populate categories select list and gallery images
			using (Db db = new Db())
			{
				model.Categories = new SelectList(db.Categories.ToList(), "Id", "Name");
			}
			model.GalleryImages = Directory.EnumerateFiles(Server.MapPath("~/Images/Uploads/Products/" + id + "/Gallery/Thumbs"))
					.Select(fn => Path.GetFileName(fn));

			// Check model state
			if (!ModelState.IsValid)
				return View(model);

			using (Db db = new Db())
			{
				//Get the product
				ProductDTO dto = db.Products.Find(model.Id);

				// Confirm product exists
				if (dto == null)
					return Content("The product does not exists.");

				// Make sure product name is unique
				if (db.Products.Where(p => p.Id != id).Any(p => p.Name == model.Name))
				{
					ModelState.AddModelError("", "That product name is taken!");
					return View(model);
				}

				// DTO the rest
				dto.Name = model.Name;
				dto.Slug = model.Name.Replace(" ", "-");
				dto.Description = model.Description;
				dto.Price = model.Price;
				dto.ImageName = model.ImageName;
				dto.CategoryId = model.CategoryId;

				CategoryDTO catDto = db.Categories.FirstOrDefault(c => c.Id == model.CategoryId);
				dto.CategoryName = catDto.Name;

				// Save DTO              
				db.SaveChanges();
			}

			// Set TempData message
			TempData["SM"] = "You have edited the product!";

			#region Image Upload

			if (file != null && file.ContentLength > 0)
			{
				// Get file extension
				string ext = file.ContentType.ToLower();

				// Verity extension
				if (ext != "image/jpg" &&
					ext != "image/jpeg" &&
					ext != "image/pjpeg" &&
					ext != "image/gif" &&

CmsShoppingCart/Areas/Admin/Views/Shop/AddProduct.cshtml
@model CmsShoppingCart.Models.ViewModels.Shop.ProductVM

@{
	ViewBag.Title = "Add Product";
}

<h2>Add Product</h2>

@if (TempData["SM"] != null)
{
	<div class="alert alert-success">
		@TempData["SM"]
	</div>
}

@*multipart/form-data: pour que leform accepte d'encrypter les images*@
@using (Html.BeginForm("AddProduct", "Shop", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		<div class="form-group">
			@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownListFor(model => model.CategoryId, Model.Categories, "Select Category", new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.ImageName, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				<input type="file" name="file" id="ImageUpload" />
				<img id="imgpreview" src="#" />
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Add Product" class="btn btn-default" />
			</div>
		</div>
	</div>
}

<div>
	@Html.ActionLink("Back to Products", "Products")
</div>


@section Scripts{

	<script>
		$(function () {

			/*
			* Preview selected image
			*/
			function readUrl(input) {
				if (input.files && input.files[0]) {
					var reader = new FileReader();

					reader.onload = function (e) {
						$("img#imgpreview").attr("src", e.target.result).width(200).height(200);
					}

					reader.readAsDataURL(input.files[0]);
				}
			}

			$("#ImageUpload").change(function () {
				readUrl(this);
			});

			///////////////////////////////////////////////////////
		});
	</script>
}

CmsShoppingCart/Areas/Admin/Views/Shop/Categories.cshtml
@model IEnumerable<CmsShoppingCart.Models.ViewModels.Shop.CategoryVM>

@{
	ViewBag.Title = "Categories";
}

<h2>Categories</h2>

<div class="new-category">
	<input type="text" id="newcategoryname" />
	<p>
		<a href="#" id="newcategorya">Add new category</a>
		<span class="ajax-text">
			<img src="~/Content/img/ajax-loader.gif" />
		</span>
	</p>
</div>

@if (!Model.Any())
{
	<h1 class="text-center">There are no categories.</h1>
}
else
{

	<table class="table sorting categories" id="pages">
		<tr class="home">
			<th>
				@Html.DisplayNameFor(model => model.Name)
			</th>
			<th></th>
		</tr>

		@foreach (var item in Model)
		{
			<tr id="id_@item.Id">
				<td>
					<div class="ajaxdivtd"></div>
					@Html.EditorFor(modelItem => item.Name, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
				</td>
				<td>
					@Html.ActionLink("Delete", "DeleteCategory", new { id = item.Id }, new { @class = "delete" })
				</td>
			</tr>
		}

	</table>

}

@section Scripts{

	<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"></script>
	<script>
        $(function () {

			/*
			* Add new category
			*/
			var newCategoryA = $("a#newcategorya");
			var newCategoryTextInput = $("#newcategoryname");
			var ajaxText = $("span.ajax-text");
			var table = $("table#pages tbody");

			newCategoryTextInput.keyup(function (e) {
				// if key = ENTER
				if (e.keyCode == 13) {
					newCategoryA.click();
				}
			});

			newCategoryA.click(function (e) {
				e.preventDefault();

				var categoryName = newCategoryTextInput.val();

				if (categoryName < 2) {
					alert("Category name must be at least 2 characters long.");
						return false;
				}

				ajaxText.show();
				var url = "/admin/shop/AddNewCategory";

				$.post(url, { categoryName: categoryName }, function (data) {
					var response = data.trim();

					if (response == "titletaken") {
						ajaxText.html("<span class='alert alert-danger'>That title is taken!</span>");
						setTimeout(function () {
							ajaxText.fadeOut("fast", function () {
								ajaxText.html("<img src=/Content/img/ajax-loader.gif />");
							});
						}, 2000);
						return false;
					} else {
						if (!$("table#pages").length) {
							location.reload();
						} else {
							ajaxText.html("<span class='alert alert-success'>That category has been added!</span>");
							setTimeout(function () {
								ajaxText.fadeOut("fast", function () {
									ajaxText.html("<img src=/Content/img/ajax-loader.gif />");
								});
							}, 2000);

							newCategoryTextInput.val("");

							var toAppend = $("table#pages tbody tr:last").clone();
							toAppend.attr("id", "id_" + data);
							toAppend.find("#item_Name").val(categoryName);
							toAppend.find("a.delete").attr("href", "/admin/shop/DeleteCategory/" + data );
							table.append(toAppend);
							table.sortable("refresh");
						}
					}
				});
			});

            ///////////////////////////////////////////////////////
			
            /*
			* Sort categories
			*/
            $("table#pages tbody").sortable({
                items: "tr:not(.home)",
                placeholder: "ui-state-highlight",
                update: function () {
                    var ids = $("table#pages tbody").sortable("serialize");
                    // Log on browser console
                    // console.log(ids);
                    var url = "/Admin/shop/ReorderCategories";

                    $.post(url, ids, function (data) {
                    });
                }
            });

			///////////////////////////////////////////////////////

            /*
			* Confirm category deletion
			*/
			$("body").on("click", "a.delete", function () {
				if (!confirm("Confirm category deletion")) return false;
			});

            ///////////////////////////////////////////////////////

            /*
			* Rename category
			*/
			var originalTextBoxValue;

			$("table#pages input.text-box").dblclick(function () {
				originalTextBoxValue = $(this).val();
				$(this).attr('readonly', false);
			});

			$("table#pages input.text-box").keyup(function (e) {
				if (e.keyCode == 13)
					$(this).blur();
			});

			$("table#pages input.text-box").blur(function () {
				var $this = $(this);
				var ajaxdiv = $this.parent().find(".ajaxdivtd");
				var newCategoryName = $this.val();
				var categoryId = $this.parent().parent().attr("id").substring(3);
				var url = "/admin/shop/RenameCategory";

				if (newCategoryName < 2) {
					alert("Category name must be at least 2 characters long.");
					$(this).attr('readonly', true);
					return false;
				}

				$.post(url, { categoryId: categoryId, newCategoryName: newCategoryName }, function (data) {
					var response = data.trim();

					if (response === "titletaken") {
						$this.val(originalTextBoxValue);
						ajaxdiv.html("<span class='alert alert-danger'>That title is taken!</span>").show();

					} else {
						ajaxdiv.html("<span class='alert alert-success'>That category name has been changed!</span>").show();
					}
					setTimeout(function () {
						ajaxdiv.fadeOut("fast", function () {
							ajaxdiv.html("");
						});
					}, 2000);
				}).done(function () {
					$this.attr("readonly", true);
				});
			});

            ///////////////////////////////////////////////////////
        });
	</script>
}

CmsShoppingCart/Areas/Admin/Views/Shop/EditProduct.cshtml
@model CmsShoppingCart.Models.ViewModels.Shop.ProductVM

@{
	ViewBag.Title = "Edit Product";
}

<h2>Edit Product</h2>

<div>
	@Html.ActionLink("Back to Products", "Products")
</div>

<style>
	input#ImageName {
		display: none;
	}
</style>

@if (TempData["SM"] != null)
{
	<div class="alert alert-success">
		@TempData["SM"]
	</div>
}

@using (Html.BeginForm("EditProduct", "Shop", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		@Html.HiddenFor(model => model.Id)

		<div class="form-group">
			@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
			</div>
		</div>


		<div class="form-group">
			@Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownListFor(model => model.CategoryId, Model.Categories, new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.ImageName, htmlAttributes: new { @class = "control-label col-md-2" })
			@Html.EditorFor(model => model.ImageName, new { htmlAttributes = new { @class = "form-control" } })
			<div class="col-md-10">
				<img src="~/Images/Uploads/Products/@Model.Id/Thumbs/@Model.ImageName" />
				<br /><br />
				<img id="imgpreview" src="#" />
				<br /><br />
				<div class="col-md-10">
					<input type="file" name="file" id="ImageUpload" />
				</div>
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Edit Product" class="btn btn-default" />
			</div>
		</div>
	</div>
}

<hr />

@if (!Model.GalleryImages.Any())
{
	<h3>There are no gallery images for this product.</h3>
}

<form action="/admin/shop/SaveGalleryImages" method="post" enctype="multipart/form-data" class="dropzone" id="dropzoneForm">
	<div class="fallback">
		<input type="file" name="file" multiple />
		<input type="submit" value="Upload" />
	</div>
</form>

<br /><br />

@foreach (var image in Model.GalleryImages)
{
	<div style="display: inline-block;margin-right:15px;">
		<img src="/Images/Uploads/Products/@Model.Id/Gallery/Thumbs/@image" />
		<br />
		@Html.ActionLink("delete", "DeleteImage", "Shop", new { @class = "deleteimage", data_name = image })
	</div>
}

<link href="~/Scripts/dropzone/basic.css" rel="stylesheet" />
<link href="~/Scripts/dropzone/dropzone.css" rel="stylesheet" />
@section Scripts{

<script src="~/Scripts/dropzone/dropzone.js"></script>
	<script>
		$(function () {

			/*
			* Preview selected image
			*/
			function readUrl(input) {
				if (input.files && input.files[0]) {
					var reader = new FileReader();

					reader.onload = function (e) {
						$("img#imgpreview").attr("src", e.target.result).width(200).height(200);
					}

					reader.readAsDataURL(input.files[0]);
				}
			}

			$("#ImageUpload").change(function () {
				readUrl(this);
			});

			///////////////////////////////////////////////////////

			/*
			* Dropzone js
			*/
			Dropzone.options.dropzoneForm = {
				acceptedFiles: "image/*",
				init: function () {
					this.on("complete", function (file) {
						if (this.getUploadingFiles().length === 0 && this.getQueuedFiles().length === 0) {
							location.reload();
						}
					});

					this.on("sending", function (xhr, formData, file) {
						formData.append("id", @Model.Id);
					});
				}
			};

			///////////////////////////////////////////////////////

			/*
			* deleteimage confirmation
			*/

			$("a.deleteimage").click(function (e) {
				e.preventDefault();

				if (!confirm("Confirm deletion")) return false;

				var $this = $(this);
				var url = "/admin/shop/DeleteImage";
				var imageName = $this.data("name");

				$.post(url, { id: @Model.Id, imageName: imageName }, function (data) {
					$this.parent().fadeOut("fast");
				});

			});

			///////////////////////////////////////////////////////

		});
	</script>
}

CmsShoppingCart/Areas/Admin/Views/Shop/Products.cshtml
@model IEnumerable<CmsShoppingCart.Models.ViewModels.Shop.ProductVM>
@using PagedList.Mvc;
@using PagedList;

@{
	ViewBag.Title = "Products";
}

<h2>Products</h2>

@if (TempData["SM"] != null)
{
	<div class="alert alert-success">
		@TempData["SM"]
	</div>
}

<select id="selectCategory" name="selectCategory">
	<option value="0">All</option>
	@foreach (var category in @ViewBag.Categories)
	{
		if (category.Value == ViewBag.SelectedCategory)
		{
			<option selected="selected" value="@category.Value">@category.Text</option>
		}
		else
		{
			<option value="@category.Value">@category.Text</option>
		}
	}
</select>

<p>
	@Html.ActionLink("Add New Product", "AddProduct")
</p>
<table class="table">
	<tr>
		<th>
			@Html.DisplayNameFor(model => model.Name)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Description)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.ImageName)
		</th>
		<th></th>
	</tr>
	@foreach (var item in ViewBag.OnePageOfProducts)
	{
		<tr>
			<td>
				@item.Name
			</td>
			<td>
				@item.Description
			</td>
			<td>
				@item.Price
			</td>
			<td>
				<a href="/admin/shop/EditProduct/@item.Id">
					<img src="/Images/Uploads/Products/@item.Id/Thumbs/@item.ImageName" />
				</a>
			</td>
			<td>
				@Html.ActionLink("Edit", "EditProduct", new { id = item.Id }) |
				@Html.ActionLink("Delete", "DeleteProduct", new { id = item.Id }, new { @class = "delete" })
			</td>
		</tr>
	}

</table>

@Html.PagedListPager((IPagedList)ViewBag.OnePageOfProducts, page => Url.Action("Products", new { page, categoryId = ViewBag.SelectedCategory }))

@section Scripts{

	<script>
		$(function () {
			
			/*
			* Confirm product deletion
			*/
			$("a.delete").click(function () {
				if (!confirm("Confirm product deletion")) return false;
			});

			/*
			* Select products from specified category
			*/
			$("#selectCategory").on("change", function () {
				var url = $(this).val();

				if (url) {
					window.location = "/admin/shop/Products?categoryId=" + url;
				}

				return false;
			});

			///////////////////////////////////////////////////////
		});
	</script>
}